#FROM public.ecr.aws/lambda/python:3.10
FROM public.ecr.aws/lambda/python:3.10-x86_64

# Copy requirements.txt
#COPY requirements.txt ${LAMBDA_TASK_ROOT}
COPY requirementsLambda.txt ${LAMBDA_TASK_ROOT}
COPY DatabaseImageMatchingLibrary ${LAMBDA_TASK_ROOT}

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY testMatching.py ${LAMBDA_TASK_ROOT}
COPY settings.json ${LAMBDA_TASK_ROOT}

#COPY SIFT.npz ${LAMBDA_TASK_ROOT}/matchingScript/
#COPY Database_Descriptors.npy ${LAMBDA_TASK_ROOT}/matchingScript/
#COPY Database_Dict.json ${LAMBDA_TASK_ROOT}/matchingScript/
#COPY Database300.json ${LAMBDA_TASK_ROOT}/matchingScript/

# Install the specified packages
#RUN pip install -r requirements.txt
#RUN apt-get update && apt-get install -y libgl1-mesa-glx
#RUN apt-get update && apt-get install -y libgl1-mesa-glx
RUN pip install -r requirementsLambda.txt

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
#CMD [ "lambda_function.handler" ]
#CMD [ "testMatching.lambda_handler" ]
CMD [ "lambda_function.lambda_handler" ]
